/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-12-08 04:02:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<title>Housing Society Management System</title>\n");
      out.write("<link href=\"templatemo_style.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/swfobject/swfobject.js\"></script>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/ddsmoothmenu.css\" />\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/ddsmoothmenu.js\">\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tddsmoothmenu.init({\n");
      out.write("\t\tmainmenuid : \"templatemo_menu\", //menu DIV id\n");
      out.write("\t\torientation : 'h', //Horizontal or vertical menu: Set to \"h\" or \"v\"\n");
      out.write("\t\tclassname : 'ddsmoothmenu', //class added to menu's outer DIV\n");
      out.write("\t\t//customtheme: [\"#1c5a80\", \"#18374a\"],\n");
      out.write("\t\tcontentsource : \"markup\" //\"markup\" or [\"container_id\", \"path_to_menu_file\"]\n");
      out.write("\t})\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<div id=\"templatemo_wrapper\">\n");
      out.write("\n");
      out.write("\t\t<div id=\"templatemo_header\">\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"site_title\">\n");
      out.write("\t\t\t\t<h1>\n");
      out.write("\t\t\t\t\t<a href=\"index.jsp\" target=\"_parent\"></a>\n");
      out.write("\t\t\t\t</h1>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"templatemo_menu\" class=\"ddsmoothmenu\">\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"about.jsp\" class=\"selected\">About</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"login.jsp\">Login</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"contact.jsp\">Contact</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<br style=\"clear: left\" />\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- end of templatemo_menu -->\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- end of header -->\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\t<div align=\"center\">\n");
      out.write("\t\n");
      out.write("\t<center><h2>Out Team Members</h2></center>\n");
      out.write("\t\t<table width=\"60%\" border=\"1\">\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td height=\"50\" width=\"400\" >\n");
      out.write("\t\t\t\t<div style=\"padding: 20px;\" align=\"center\">\n");
      out.write("\t\t\t\t<img alt=\"Sushil Dangi\" height=\"160px\" width=\"150px\" src=\"profile/sushil.jpeg\"/><br><br>\n");
      out.write("\t\t\t\t<b>Name : Sushil Dangi</b><br>\n");
      out.write("\t\t\t\t<b>Roll No. : 14223077</b>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t\t<td height=\"50\" width=\"400\" >\n");
      out.write("\t\t\t\t<div style=\"padding: 20px\" align=\"center\">\n");
      out.write("\t\t\t\t<img alt=\"Animikh Daripa\" height=\"160px\" width=\"150px\" src=\"profile/animikh.jpeg\"/><br><br>\n");
      out.write("\t\t\t\t<b>Name : Animikh Daripa</b><br>\n");
      out.write("\t\t\t\t<b>Roll No. : 14223014</b>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td height=\"50\" width=\"400\" >\n");
      out.write("\t\t\t\t<div style=\"padding: 20px\" align=\"center\">\n");
      out.write("\t\t\t\t<img alt=\"Avinash Singh\" height=\"160px\" width=\"150px\" src=\"profile/avinash.jpeg\"/><br><br>\n");
      out.write("\t\t\t\t<b>Name : Avinash Singh </b><br>\n");
      out.write("\t\t\t\t<b>Roll No. : 14223025</b>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t</td><td height=\"50\" width=\"400\" >\n");
      out.write("\t\t\t\t<div style=\"padding: 20px\" align=\"center\">\n");
      out.write("\t\t\t\t<img alt=\"Jaya Gupta\" height=\"160px\" width=\"150px\" src=\"profile/java.jpeg\"/><br><br>\n");
      out.write("\t\t\t\t<b>Name : Jaya Gupta</b><br>\n");
      out.write("\t\t\t\t<b>Roll No. : 14223040</b>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</table>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div id=\"templatemo_footer_wrapper\">\n");
      out.write("\t\t<div id=\"templatemo_footer\">\n");
      out.write("\t\t\tCopyright © 2016 <a href=\"#\">Housing Management System</a>\n");
      out.write("\t\t\t<div class=\"cleaner\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
