/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-12-06 06:16:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import sdm.hsmp.jdbc.DriverConnection;

public final class mchngpass_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("sdm.hsmp.jdbc.DriverConnection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");

	String myname = (String) session.getAttribute("uname");
	String type = (String) session.getAttribute("utype");
	if (myname == null || type == null || !type.equalsIgnoreCase("member")) {
		response.sendRedirect("kill.jsp");
	}

      out.write("\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<title>Housing Society Management System</title>\n");
      out.write("<link href=\"templatemo_style.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/swfobject/swfobject.js\"></script>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/ddsmoothmenu.css\" />\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/ddsmoothmenu.js\">\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tddsmoothmenu.init({\n");
      out.write("\t\tmainmenuid : \"templatemo_menu\", //menu DIV id\n");
      out.write("\t\torientation : 'h', //Horizontal or vertical menu: Set to \"h\" or \"v\"\n");
      out.write("\t\tclassname : 'ddsmoothmenu', //class added to menu's outer DIV\n");
      out.write("\t\t//customtheme: [\"#1c5a80\", \"#18374a\"],\n");
      out.write("\t\tcontentsource : \"markup\" //\"markup\" or [\"container_id\", \"path_to_menu_file\"]\n");
      out.write("\t})\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<form action=\"mchngpass\" method=\"post\">\n");
      out.write("\t<div id=\"templatemo_wrapper\">\n");
      out.write("\n");
      out.write("\t\t<div id=\"templatemo_header\">\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"site_title\">\n");
      out.write("\t\t\t\t<h1>\n");
      out.write("\t\t\t\t\t<a href=\"#\" target=\"_parent\"></a>\n");
      out.write("\t\t\t\t</h1>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"templatemo_menu\" class=\"ddsmoothmenu\">\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li><a href=\"memhome.jsp\" class=\"selected\">Home</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"viewbill.jsp\">View Bill</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"mchngpass.jsp\">change Password</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"kill.jsp\">Logout</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<br style=\"clear: left\" />\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- end of templatemo_menu -->\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- end of header -->\n");
      out.write("\t\t\n");
      out.write("\t\t<table width=\"100%\" height=\"451\" border=\"0\" align=\"center\"\n");
      out.write("\t\t\tcellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td height=\"451\" align=\"center\" valign=\"middle\" bgcolor=\"#d2d6de\"><table\n");
      out.write("\t\t\t\t\t\twidth=\"424\" height=\"331\" border=\"0\" align=\"center\" cellpadding=\"0\"\n");
      out.write("\t\t\t\t\t\tcellspacing=\"0\">\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td height=\"89\" align=\"center\" valign=\"middle\"><img\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"images/cp.jpeg\" width=\"233\" height=\"90\" /></td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td height=\"237\" align=\"center\" valign=\"middle\"><table\n");
      out.write("\t\t\t\t\t\t\t\t\twidth=\"356\" height=\"205\" border=\"0\" align=\"center\"\n");
      out.write("\t\t\t\t\t\t\t\t\tcellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td height=\"190\" align=\"left\" valign=\"middle\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tbgcolor=\"#FFFFFF\" style=\"border: 1px solid #46433e;\"><table\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\twidth=\"322\" border=\"0\" align=\"center\" cellpadding=\"6\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tcellspacing=\"0\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"2\" align=\"center\" valign=\"top\">Change\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tYour password\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<font color=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</font>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"273\" align=\"left\" valign=\"top\"><input\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"pass\" type=\"password\" placeholder=\"Password\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tsize=\"40\" /></td>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\" valign=\"top\"><input type=\"password\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\" New Password\" title=\"Must Be upper , lower , special and number\" size=\"40\" required\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tpattern=\"(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{6,}\" name=\"pwd1\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tonchange=\"form.pwd2.pattern = this.value;\"></td>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\" valign=\"top\"><input type=\"password\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\" Conferm Password\" size=\"40\" required title=\"Must Be upper , lower , special and number Matching\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tpattern=\"(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{6,}\" name=\"pwd2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"2\" align=\"right\" valign=\"top\"><input\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"submit\" class=\"submit_btn\" value=\"Change\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 100px; height: 40px\" /></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</table></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t</table></td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t</table></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t</table>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div id=\"templatemo_footer_wrapper\">\n");
      out.write("\t\t<div id=\"templatemo_footer\">\n");
      out.write("\t\t\tCopyright © 2016 <a href=\"#\">Housing Management System</a>\n");
      out.write("\t\t\t<div class=\"cleaner\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
